services:
  inferio:
    restart: unless-stopped
    build: .
    container_name: inferio
    environment:
      - INFERIO_HOST=0.0.0.0
      - INFERIO_PORT=7777
      - LOGLEVEL=INFO
      - LOGS_FILE=/logs/inferio.log
      #- JINA_API_KEY=${JINA_API}
      #- JINA_TIMEOUT=15
      #- NO_CUDNN=true
    volumes:
      - ./inferio:/logs
      - ./cudnn:/app/cudnn
      - ./cache:/home/ubuntu/.cache
    entrypoint: [ "bash", "./inferio-start.sh" ]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
  panoptikon:
    restart: unless-stopped
    build: .
    container_name: panoptikon
    environment:
      - HOST=0.0.0.0
      - PORT=6342
      - DATA_FOLDER=data
      - LOGLEVEL=INFO
      - ENABLE_CLIENT=false
      - DISABLE_CLIENT_UPDATE=true
      - NO_CUDNN=true
      - INFERENCE_API_URL=http://inferio:7777
    volumes:
      - ./data:/app/data
      - ${FILE_FOLDER_PATH}:/files
    depends_on:
      - inferio
  panoptikon-ui-private:
    restart: unless-stopped
    # Normal Mode (Private)
    image: ghcr.io/reasv/panoptikon-ui:master
    container_name: panoptikon-ui-private
    environment:
      - PANOPTIKON_API_URL=http://panoptikon:6342
      - INFERENCE_API_URL=http://inferio:7777
      - RESTRICTED_MODE=false
    depends_on:
      - panoptikon

  panoptikon-ui-public:
    restart: unless-stopped
    # Restricted Mode (Public)
    image: ghcr.io/reasv/panoptikon-ui:master
    container_name: panoptikon-ui-public
    environment:
      - PANOPTIKON_API_URL=http://panoptikon:6342
      - INFERENCE_API_URL=http://inferio:7777
      - RESTRICTED_MODE=true
    depends_on:
      - panoptikon

  nginx:
    restart: unless-stopped
    image: nginx:latest
    container_name: nginx
    ports:
      - "6339:80" # Exposed port for Restricted Mode (Public)
      - "6340:8080" # Exposed port for Normal Mode (Private)
    volumes:
      - ./nginx-config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - panoptikon-ui-private
      - panoptikon-ui-public
      - panoptikon
