#!/usr/bin/env python3
"""Write config/server/nix-dev.toml for `nix develop` (bare tool names, no store paths).

Prints absolute path on stdout for PANOPTIKON_CONFIG_PATH.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SRC = REPO_ROOT / "config" / "server" / "default.toml"
DST = REPO_ROOT / "config" / "server" / "nix-dev.toml"

HEADER = """\
# AUTO-GENERATED by nix develop — do not edit or commit.
# Bare tool names; host_paths + PATH resolve them.

"""

OVERRIDES: dict[str, dict[str, str]] = {
    "upstreams.ui": {"node": "node"},
    "jobs": {
        "ffmpeg": "ffmpeg",
        "ffprobe": "ffprobe",
    },
}


def _toml_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def apply_section_keys(text: str, sections: dict[str, dict[str, str]]) -> str:
    lines = text.splitlines(keepends=True)
    out: list[str] = []
    pending: dict[str, str] = {}
    written: set[str] = set()
    section_header = re.compile(r"^\[([^\]]+)\]\s*(?:#.*)?$")
    assignment = re.compile(r"^([A-Za-z_][A-Za-z0-9_]*)\s*=")

    def flush_pending() -> None:
        nonlocal pending, written
        for key, value in pending.items():
            if key not in written:
                out.append(f"{key} = {_toml_string(value)}\n")
        pending = {}
        written = set()

    for line in lines:
        header = section_header.match(line)
        if header:
            flush_pending()
            out.append(line)
            pending = dict(sections.get(header.group(1), {}))
            written = set()
            continue

        if pending:
            m = assignment.match(line)
            if m and m.group(1) in pending:
                key = m.group(1)
                out.append(f"{key} = {_toml_string(pending[key])}\n")
                written.add(key)
                continue

        out.append(line)

    flush_pending()
    return "".join(out)


def main() -> int:
    if not SRC.is_file():
        print(f"error: missing {SRC}", file=sys.stderr)
        return 1
    DST.parent.mkdir(parents=True, exist_ok=True)
    DST.write_text(
        HEADER + apply_section_keys(SRC.read_text(encoding="utf-8"), OVERRIDES),
        encoding="utf-8",
    )
    print(DST.resolve())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
