use utoipa::OpenApi;
use utoipa::Modify;
use utoipa::openapi::schema::{ObjectBuilder, Schema, SchemaType};

struct JsonValueSchema;

impl Modify for JsonValueSchema {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        let components = openapi.components.get_or_insert_with(Default::default);
        components.schemas.insert(
            "Value".to_string(),
            Schema::Object(
                ObjectBuilder::new()
                    .schema_type(SchemaType::AnyValue)
                    .build(),
            )
            .into(),
        );
    }
}

#[derive(OpenApi)]
#[openapi(
    paths(
        crate::api::search::search_pql,
        crate::api::search::search_pql_build,
        crate::api::search::get_search_cache,
        crate::api::search::clear_search_cache,
        crate::api::search::get_tags,
        crate::api::search::get_top_tags,
        crate::api::search::get_stats,
        crate::api::items::item_meta,
        crate::api::items::item_file,
        crate::api::items::item_thumbnail,
        crate::api::items::item_text,
        crate::api::items::item_tags,
        crate::api::items::texts_any,
        crate::api::open::open_file_on_host,
        crate::api::open::show_in_file_manager,
        crate::api::jobs::queue_status,
        crate::api::jobs::enqueue_data_extraction,
        crate::api::jobs::enqueue_delete_extracted_data,
        crate::api::jobs::enqueue_folder_rescan,
        crate::api::jobs::enqueue_update_folders,
        crate::api::jobs::cancel_queued,
        crate::api::jobs::cancel_current_job,
        crate::api::jobs::get_folders,
        crate::api::jobs::get_scan_history,
        crate::api::jobs::delete_scan_data,
        crate::api::jobs::get_extraction_history,
        crate::api::jobs::update_config,
        crate::api::jobs::get_config,
        crate::api::jobs::get_setter_data_count,
        crate::api::jobs::manual_trigger_cronjob,
        crate::api::bookmarks::bookmark_namespaces,
        crate::api::bookmarks::bookmark_users,
        crate::api::bookmarks::bookmarks_by_namespace,
        crate::api::bookmarks::delete_bookmarks_by_namespace,
        crate::api::bookmarks::add_bookmarks_by_namespace,
        crate::api::bookmarks::get_bookmark,
        crate::api::bookmarks::add_bookmark_by_sha256,
        crate::api::bookmarks::delete_bookmark_by_sha256,
        crate::api::bookmarks::bookmarks_item,
        crate::api::db::db_info,
        crate::api::db::db_create
    ),
    components(
        schemas(
            crate::api::search::SearchMetrics,
            crate::api::search::CompiledQuery,
            crate::api::search::PqlBuildResponse,
            crate::api::search::SearchResult,
            crate::api::search::FileSearchResponse,
            crate::api::search::TagSearchResults,
            crate::api::search::TagFrequency,
            crate::api::search::TagStats,
            crate::api::search::FileStats,
            crate::api::search::ExtractedTextStats,
            crate::api::search::SearchStats,
            crate::api::items::ItemMetadataResponse,
            crate::api::items::ItemRecordResponse,
            crate::api::items::FileRecordResponse,
            crate::api::items::TextResponse,
            crate::api::items::TagResponse,
            crate::api::open::OpenResponse,
            crate::api::jobs::QueueCancelResponse,
            crate::api::jobs::CancelResponse,
            crate::api::jobs::FoldersResponse,
            crate::api::jobs::SetterDataStats,
            crate::api::jobs::CronJobResponse,
            crate::jobs::queue::JobModel,
            crate::jobs::queue::QueueStatusModel,
            crate::jobs::queue::JobType,
            crate::db::file_scans::FileScanRecord,
            crate::db::extraction_log::LogRecord,
            crate::db::system_config::SystemConfig,
            crate::db::system_config::CronJob,
            crate::db::system_config::JobSettings,
            crate::db::items::ExtractedTextRecord,
            crate::db::items::ItemIdentifierType,
            crate::api::bookmarks::BookmarkNamespaces,
            crate::api::bookmarks::BookmarkUsers,
            crate::api::bookmarks::Results,
            crate::api::bookmarks::FileSearchResult,
            crate::api::bookmarks::ExistingBookmarkMetadata,
            crate::api::bookmarks::ItemBookmarks,
            crate::api::bookmarks::BookmarkMetadata,
            crate::api::bookmarks::MessageResult,
            crate::api::bookmarks::Items,
            crate::api::bookmarks::ItemsMeta,
            crate::api::bookmarks::BookmarkOrderBy,
            crate::api::bookmarks::SortOrder,
            crate::policy::DbInfo,
            crate::policy::SingleDbInfo,
            crate::api::db::DbCreateResponse,
            crate::pql::EmbeddingCacheEntry,
            crate::pql::EmbeddingCacheStats,
            crate::pql::model::PqlQuery,
            crate::pql::model::QueryElement,
            crate::pql::model::AndOperator,
            crate::pql::model::OrOperator,
            crate::pql::model::NotOperator,
            crate::pql::model::EntityType,
            crate::pql::model::Column,
            crate::pql::model::OrderByField,
            crate::pql::model::OrderDirection,
            crate::pql::model::ScalarValue,
            crate::pql::model::SortableOptions,
            crate::pql::model::OrderArgs,
            crate::pql::model::Rrf,
            crate::pql::model::Match,
            crate::pql::model::MatchAnd,
            crate::pql::model::MatchOr,
            crate::pql::model::MatchNot,
            crate::pql::model::MatchOps,
            crate::pql::model::MatchValue,
            crate::pql::model::MatchValues,
            crate::pql::model::Matches,
            crate::pql::model::MatchPath,
            crate::pql::model::MatchPathArgs,
            crate::pql::model::MatchText,
            crate::pql::model::MatchTextArgs,
            crate::pql::model::MatchTags,
            crate::pql::model::TagsArgs,
            crate::pql::model::InBookmarks,
            crate::pql::model::InBookmarksArgs,
            crate::pql::model::ProcessedBy,
            crate::pql::model::HasUnprocessedData,
            crate::pql::model::DerivedDataArgs,
            crate::pql::model::SemanticTextSearch,
            crate::pql::model::SemanticTextArgs,
            crate::pql::model::SemanticImageSearch,
            crate::pql::model::SemanticImageArgs,
            crate::pql::model::SimilarTo,
            crate::pql::model::SimilarityArgs,
            crate::pql::model::SourceArgs,
            crate::pql::model::DistanceAggregation,
            crate::pql::model::DistanceFunction,
            crate::pql::model::EmbedArgs
        )
    ),
    tags(
        (name = "search", description = "Search and PQL endpoints"),
        (name = "items"),
        (name = "open"),
        (name = "jobs"),
        (name = "bookmarks"),
        (name = "database")
    ),
    modifiers(&JsonValueSchema)
)]
#[allow(dead_code)]
pub struct ApiDoc;
