use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
    paths(
        crate::api::search::search_pql,
        crate::api::search::search_pql_build,
        crate::api::search::get_search_cache,
        crate::api::search::clear_search_cache,
        crate::api::search::get_tags,
        crate::api::search::get_top_tags,
        crate::api::search::get_stats
    ),
    components(
        schemas(
            crate::api::search::SearchMetrics,
            crate::api::search::CompiledQuery,
            crate::api::search::PqlBuildResponse,
            crate::api::search::SearchResult,
            crate::api::search::FileSearchResponse,
            crate::api::search::TagSearchResults,
            crate::api::search::TagFrequency,
            crate::api::search::TagStats,
            crate::api::search::FileStats,
            crate::api::search::ExtractedTextStats,
            crate::api::search::SearchStats,
            crate::pql::EmbeddingCacheEntry,
            crate::pql::EmbeddingCacheStats,
            crate::pql::model::PqlQuery,
            crate::pql::model::QueryElement,
            crate::pql::model::AndOperator,
            crate::pql::model::OrOperator,
            crate::pql::model::NotOperator,
            crate::pql::model::EntityType,
            crate::pql::model::Column,
            crate::pql::model::OrderByField,
            crate::pql::model::OrderDirection,
            crate::pql::model::ScalarValue,
            crate::pql::model::SortableOptions,
            crate::pql::model::OrderArgs,
            crate::pql::model::Rrf,
            crate::pql::model::Match,
            crate::pql::model::MatchAnd,
            crate::pql::model::MatchOr,
            crate::pql::model::MatchNot,
            crate::pql::model::MatchOps,
            crate::pql::model::MatchValue,
            crate::pql::model::MatchValues,
            crate::pql::model::Matches,
            crate::pql::model::MatchPath,
            crate::pql::model::MatchPathArgs,
            crate::pql::model::MatchText,
            crate::pql::model::MatchTextArgs,
            crate::pql::model::MatchTags,
            crate::pql::model::TagsArgs,
            crate::pql::model::InBookmarks,
            crate::pql::model::InBookmarksArgs,
            crate::pql::model::ProcessedBy,
            crate::pql::model::HasUnprocessedData,
            crate::pql::model::DerivedDataArgs,
            crate::pql::model::SemanticTextSearch,
            crate::pql::model::SemanticTextArgs,
            crate::pql::model::SemanticImageSearch,
            crate::pql::model::SemanticImageArgs,
            crate::pql::model::SimilarTo,
            crate::pql::model::SimilarityArgs,
            crate::pql::model::SourceArgs,
            crate::pql::model::DistanceAggregation,
            crate::pql::model::DistanceFunction,
            crate::pql::model::EmbedArgs
        )
    ),
    tags(
        (name = "search", description = "Search and PQL endpoints")
    )
)]
#[allow(dead_code)]
pub struct ApiDoc;
